### ISSUE TITLE
Databundle: add h2 cavern storage potentials

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur-sec#205]

**Comment by jensch33** [comment]
Hello Fabian,
just to be sure: Does this refer to the missing `h2_salt_caverns_GWh_per_sqkm.geojson` in https://zenodo.org/record/5546517 ? May I ask what is the simplest caveat to run the current release of the model without this piece of data? Just commenting out lines 283 to 293 in the snakefile seems to be no way forward...

**Comment by fneum** [comment]
Yes, that's correct. We usually update the zenodo bundle with new releases (we have planned the next release for the upcoming week). 

The easiest way is to check out a commit before the salt caverns were added `git checkout ad7dd1aa3f689d214d029d6810f698bb616a6515`

Possible also that disabling hydrogen underground storage in the config and commenting

https://github.com/PyPSA/pypsa-eur-sec/blob/510ef20937c0cab0508f2afcee87f67044fe59c2/Snakefile#L444

gets it to work.

**Comment by fneum** [comment]
`master` should work now, too with updated data bundle.

**Comment by jensch33** [comment]
Excellent, thank you very much!
Maybe also the documentation of the data requirements in the docs (https://zenodo.org/record/5824485/files/pypsa-eur-sec-data-bundle.tar.gz) should be updated with the new Zenodo link to avoid confusion? (don't want to go through the whole forking procedure to propose the change of just one link)

**Comment by fneum** [comment]
Of course, I missed that.
