### ISSUE TITLE
Approx. due date for release 0.7

### ISSUE THREAD

**Issue by ulfmueller** [PyPSA/pypsa-eur-sec#214]
Dear developers,

do you have any rough estimate when you will be able to release the next release? 

Many thanks for your great work!

**Comment by fneum** [comment]
I have planned to do this within the first two weeks of January.

**Comment by ulfmueller** [comment]
Any new guess for a release date? Just ignore, if this is annoying you...

**Comment by fneum** [comment]
No, it's fine to ask, but for the release pipeline PyPSA -> PyPSA-Eur -> PyPSA-Eur-Sec with a few outstanding issues to meet the next milestone. Do you need the release for a particulary purpose? It's fine to use the `master`. The data bundle has already been updated to include the salt caverns.

**Comment by ulfmueller** [comment]
Within the project eGon we generate a quite extensive data model for our tools and p-e-s is one task in a big airflow pipeline. Actually we are using a p-e-s fork in which we parametrize p-e-s as we like. And well, I wanted to end that development for now and get a clean release from your side as a nice referring point. I am just a bit afraid if I take the master now, integrate everything well that once the release is there it would create sort of double work. So I was thinking either wait a bit longer or go for the current master and hope that later on the new release does not present any big changes...
