### ISSUE TITLE
Include geological potentials for salt cavern storage of hydrogen

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur-sec#23]
Also include a limit that the power input/output per day cannot be more than 10% of the energy capacity, to avoid stress and cracks, see https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/760479/H2_supply_chain_evidence_-_publication_version.pdf

**Comment by nworbmot** [comment]
This has been done in https://github.com/PyPSA/pypsa-eur-sec/pull/69 on a per-country basis, but not yet localised - for this we need the geodata from the above paper.

**Comment by fneum** [comment]
This will be fixed by #191.
