### ISSUE TITLE
Distribute international shipping demand by turnover of ports

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur-sec#276]
https://datacatalog.worldbank.org/search/dataset/0038118/Global---International-Ports

JSON file has all the international ports with trade volumes and locations.

**Comment by euronion** [comment]
National shipping demand ("total domestic navigation") needs different aggregation. Can not be fully neglected when disaggregated:
![grafik](https://user-images.githubusercontent.com/42553970/201368660-fad95ab0-87a1-4ba7-93ce-35c4e5d901c7.png)

DG transport or RIS (River-Information-System) by EU might be potential starting points for disagg datasource.
Alternatively: Waterways or AIS movement for national shipping.
