### ISSUE TITLE
Add potentials for rooftop PV

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur-sec#61]
Since we separated low- and high-voltage nodes, we've been optimizing utility PV and rooftop PV separately. The PV installable potentials were set based on land use, but we should develop separate installable potentials for rooftop PV.

According to this [JRC paper](https://doi.org/10.1016/j.rser.2019.109309) EU28 rooftops could produce 680 TWh/a but this [summary of other JRC work](http://www.europeanenergyinnovation.eu/Articles/Spring-2018/The-Rooftop-Potential-for-PV-Systems-in-the-European-Union-to-deliver-the-Paris-Agreement) suggests 1500 TWh/a for the EU28?

Are they distinguishing between residential, tertiary and industrial properties?

@martavp Do you have any good sources for this?

**Comment by fneum** [comment]
Would also impact `build_renewable_profiles` rule in PyPSA-Eur, right?

**Comment by nworbmot** [comment]
Yes you're right. I think the main issue is the distribution of angles to the azimuth etc, which will be varied for rooftop, versus fairly uniform for utility PV.

**Comment by martavp** [comment]
The usual proxy is to estimate rooftop potential based on population density. 

A per-capita rooftop PV potential of 1kW/person can be estimated with reasonable assumptions: 
10m2/person * 150W/m2 (15% efficiency) * 0.9 inverter efficiency * 0.75 (of the rooftop space useful) = 1 kW/person

This [JRC-TIMES report](https://ec.europa.eu/jrc/en/publication/eur-scientific-and-technical-research-reports/jrc-eu-times-model-assessing-long-term-role-set-plan-energy-technologies) also assumes 10m2 per capita, and the total rooftop area of 7935 km estimated with the[ high-resolution geospatial assessment](https://www.sciencedirect.com/science/article/pii/S1364032119305179?via%3Dihub) also fits well with that number. 

This approach results in a potential capacity of 740 GW, with 1100 equivalent hours, this will produce 800 TWh/a which is similar to the figures that you have found Tom. 

For the time series, what [ninja does](https://www.sciencedirect.com/science/article/pii/S0360544216311744), and what I did in [this paper](https://arxiv.org/abs/1807.10044), is assuming that tilt and orientation angles of installations follow two Gaussian distributions whose average are the optimum values (tilt=latitude, orientation=south). This creates some smoothing of the peak capacity factors which slightly increases the smoothing that is already created by spatial integration.

**Comment by nworbmot** [comment]
Brilliant, thank you @martavp! @lisazeyen and I have seen big swings between rooftop and utility depending on the grid connection costs, but given that the rooftop potential is lower than half the total PV we see installed with the sector-coupled model, I think we can just max out the rooftop potential and then do the rest utility (also with agrovoltaics). We can ditch the 50-50% split from previous work.

**Comment by martavp** [comment]
Yes, I agree. Rooftop should be prioritized and Agrivoltaics is the way to go in southern Europe, it saves water and reduces land competition. 

In the future, we can estimate the potential of agrivoltaics assuming a lower power density and considering the [Corine Land Cover categories](https://land.copernicus.eu/eagle/files/eagle-related-projects/pt_clc-conversion-to-fao-lccs3_dec2010) 21 (Land principally occupied by agriculture, with significant areas of natural vegetation ) and 22 (Agro-forestry areas ). Those are [currently excluded ](https://github.com/PyPSA/pypsa-eur/blob/bb3477cd693d1c8e77e75e61a1a7e1a4647e6a3c/config.default.yaml#L132) when the available land for PV is estimated.

**Comment by euronion** [comment]
> The usual proxy is to estimate rooftop potential based on population density.

Corine also includes "Continuous urban fabric" and "Discontinuous urban fabric". Could this somehow be more accurate (or less)?

**Comment by martavp** [comment]
That will be less accurate since they include areas identified as "urban", but not the rooftop area available.

**Comment by lisazeyen** [comment]
For calculating the retrofitting potentials per country I was using data from the hotmaps project, which does include also informations about roofs for EU countries (percentage of flat/tilted roofs/ number of dwellings per building type / type of buildings (Multi-family, apartment, office). Maybe one could use also this data to calculate the potential? You can find the data in the branch retrofitting, under data/retro/data_building_stock.csv

**Comment by nworbmot** [comment]
Another reference: https://doi.org/10.1016/j.esr.2019.100388, implemented in https://github.com/timtroendle/euro-calliope, uses satellite pictures to assess rooftop potentials. "Two studies assess the technical potential of roof-mounted PV at the continental level, finding potentials of 840 TWh/a [26] and 1500 TWh/a [28]." The potentials in that paper look much higher, but I only find country-level results in the Appendix, not the totals, grrr....

**Comment by nworbmot** [comment]
This was done with a simplified assumption of 1 kWp/m² in https://github.com/PyPSA/pypsa-eur-sec/pull/66.
