### ISSUE TITLE
Fix unicode error with new version of snakemake

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur-sec#79]
There is a unicode dash "–" just before "sawdust" in the ``config.yaml``

https://github.com/PyPSA/pypsa-eur-sec/blob/1ea31f0e57efa0ebb0079c1ee6ea170297e5c962/config.default.yaml#L63

In the new 5.30.1 version of ``snakemake`` this causes an error since it cannot be converted to ascii encoding. This wasn't a problem in versions 5.20.1 and before.

**Comment by martavp** [comment]
A quick fix is provided in [this commit](https://github.com/martavp/pypsa-eur-sec/commit/7479ba0424ad95d531094ee7313d76e83e05c281). If you were considering a more elegant solution just ignore this one
