### ISSUE TITLE
Change "YearCommissioned" to "DataIn" in add_existing_baseyear

### ISSUE THREAD

**Issue by martavp** [PyPSA/pypsa-eur-sec#85]
This is solved in [this commit](https://github.com/martavp/pypsa-eur-sec/commit/3ae8021cb69f18d7a80efc6d92b082ccf06f469a). I will create a pull request including this change soon.

**Comment by martavp** [comment]
Fix proposed in [this commit](https://github.com/martavp/pypsa-eur-sec/commit/3ae8021cb69f18d7a80efc6d92b082ccf06f469a)

**Comment by nworbmot** [comment]
Solved in https://github.com/PyPSA/pypsa-eur-sec/pull/88.
